---
title: "Butterfly monitoring schemes: Land cover analysis"
output: html_document
params:
    transects: NA
    country: NA
    country_iso_a3: NA
    scheme_id: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "..")

## Load libraries
library(tidyverse)
library(ggplot2)
library(forcats)
```

```{r dynamic_text, include=FALSE}
## Function to check if years are sequential
is.sequential <- function(x){
  all(abs(diff(x)) == 1)
}  

seq_years <- is.sequential(as.numeric(years))

## Format years list for dynamic text
if (length(years) == 1) {
    years_formatted <- years[1]
} else if (length(years) > 1 & seq_years) {
    years_formatted <- paste0(min(years), "-", max(years))
} else if (length(years) > 1 & !seq_years) {
    years_formatted <- paste(years, sep = ", ")
}

## Format list of schemes
schemes_formatted <- paste(params$scheme_id, sep = ", ")
```

## `r params$country`

This analysis covers transects surveyed during `r years_formatted` and includes the following schemes: `r schemes_formatted`

```{r clc_labels, include=FALSE}
## Set labels for CLC values
clc_labels <- data.frame(
  clc = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11),
        #   253, 254, 255),  # Excluding non-valid values
  clc_lab = c("Sealed",
              "Woody needle leaved trees",
              "Woody broadleaved deciduous trees",
              "Woody broadleaved evergreen trees",
              "Low-growing woody plants",
              "Permanent herbaceous",
              "Periodically herbaceous",
              "Lichens and mosses",
              "Non and sparsely vegetated",
              "Water",
              "Snow and ice")
            #   "Coastal seawater buffer",
            #   "Outside area",
            #   "No data")
)
```

```{r clc_comparison, include=FALSE}
## Join transects summary to country summary
clc_compare <- summary_country %>%
    full_join(summary_transects, by = "clc", suffix = c("_country", "_transects")) %>%
    dplyr::select(clc, perc_country, perc_transects, percweighted_transects = perc_weighted) %>%
    mutate(percweighted_country = perc_country)

## Reshape to tidy data format
clc_compare <- clc_compare %>%
    pivot_longer(c("perc_country", "perc_transects", "percweighted_transects", "percweighted_country"),
                 names_to = c("measure", "area"),
                 names_sep = "_"
                 )

## Add CLC labels and tidy up data for plot
clc_compare <- clc_compare %>%
    full_join(clc_labels, by = "clc") %>%
    replace_na(list(value = 0)) %>%
    mutate(clc_lab = fct_reorder(clc_lab, value),
           area = case_when(area == "transects" ~ "Transects",
                            area == "country" ~ country)) %>%
    mutate(area = factor(area, levels = c("Transects", country)))
```

### Where are the transects located?
```{r transect_map_prep, echo=FALSE, include=FALSE}
## Get country boundaries
country_vec <- rnaturalearth::ne_countries(geounit = params$country, type = "map_units", scale = "medium", returnclass = "sf") %>%
  filter(iso_a3 == params$country_iso_a3) %>%
  st_transform(crs = 3035)

## Read in transect coordinates
transects <- read_csv("data/whole_ebms_extract_2020_2024_for_ukceh_land_cover_analysis_extracted_on_20251121/ebms_transect_coord.csv")

## Read in eBMS transect coordinates
transects_scheme <- params$transects %>% 
    filter(bms_id %in% params$scheme_id) %>%
    dplyr::select(transect_lon, transect_lat) %>%
    drop_na() %>%
    distinct()

transects_scheme_sf <- st_as_sf(transects_scheme, coords = c("transect_lon", "transect_lat"), crs = 3035)
```

```{r transect_map, fig.cap=paste0("Locations of transects surveyed in ", params$country, " (", years_formatted, ")"), echo=FALSE}
## Plot transect locations onto country map
ggplot() +
    geom_sf(data = country_vec, fill = "white", colour = "black") +
    geom_sf(data = transects_scheme_sf, colour = "#D7B7AA") +
    theme_minimal() +
    theme(panel.grid = element_line(color = NA),
          axis.text = element_blank()
         )
```

### How representative are the transects of the land cover types present in the scheme area?

```{r clc_comparison_plot, dpi=300, fig.width=7, fig.height=6, fig.cap="Proportion of transects and scheme area comprised of each Corine Land Cover classification", echo=FALSE}
## Create colour palette
fill_pal <- c("#D7B7AA", "#FFFFFF")
line_pal <- c("#D7B7AA", "black")

clc_compare %>%
    filter(measure == "percweighted") %>%
    ggplot(aes(y = clc_lab, x = value, fill = area, colour = area)) +
    geom_col(width = 0.7, position = position_dodge(0.7)) +
    xlab("Proportion of area (%)") +
    ylab("Corine Land Cover classification") +
    theme_minimal() +
    theme(axis.title.y = element_blank(),
          legend.title = element_blank(),
          legend.position="bottom") +
    scale_fill_manual(values = fill_pal,
                      guide = guide_legend(reverse = TRUE)) +
    scale_colour_manual(values = line_pal,
                      guide = guide_legend(reverse = TRUE))
```
